<?php

declare (strict_types=1);
/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 */
namespace Presta_Shop\Module\Faceted_Search\Form\Feature;

use Context;
use Presta_Shop\Module\Faceted_Search\Constraint\Url_Segment;
use Presta_Shop_Bundle\Form\Admin\Type\Switch_Type;
use Presta_Shop_Bundle\Form\Admin\Type\Translatable_Type;
use Presta_Shop_Bundle\Translation\Data_Collector_Translator;
use Presta_Shop_Bundle\Translation\Translator_Component;
use Symfony\Component\Form\Form_Builder_Interface;
/**
 * Adds module specific fields to BO form
 */
class Form_Modifier
{
    /**
     * @var Context
     */
    private $context;
    public function __construct(Context $context)
    {
        $this->context = $context;
    }
    public function modify(Form_Builder_Interface $form_builder, array $data): void
    {
        /** @var DataCollectorTranslator|TranslatorComponent $translator */
        $translator = $this->context->get_translator();
        $invalid_chars_hint = $translator->trans('Invalid characters: <>;=#{}_', [], 'Modules.Facetedsearch.Admin');
        $url_tip = $translator->trans('When the Faceted Search module is enabled, you can get more detailed URLs by choosing ' . 'the word that best represents this feature. By default, PrestaShop uses the ' . 'feature\'s name, but you can change that setting using this field.', [], 'Modules.Facetedsearch.Admin');
        $meta_title_tip = $translator->trans('When the Faceted Search module is enabled, you can get more detailed page titles by ' . 'choosing the word that best represents this feature. By default, PrestaShop uses the ' . 'feature\'s name, but you can change that setting using this field.', [], 'Modules.Facetedsearch.Admin');
        $form_builder->add('url_name', Translatable_Type::class, ['required' => false, 'label' => $translator->trans('URL', [], 'Modules.Facetedsearch.Admin'), 'help' => $url_tip . ' ' . $invalid_chars_hint, 'options' => ['constraints' => [new Url_Segment(['message' => $translator->trans('%s is invalid.', [], 'Admin.Notifications.Error')])]], 'data' => $data['url']])->add('meta_title', Translatable_Type::class, ['required' => false, 'label' => $translator->trans('Meta title', [], 'Modules.Facetedsearch.Admin'), 'help' => $meta_title_tip, 'data' => $data['meta_title']])->add('layered_indexable', Switch_Type::class, ['required' => false, 'label' => $translator->trans('Indexable', [], 'Modules.Facetedsearch.Admin'), 'help' => $translator->trans('Use this attribute in URL generated by the Faceted Search module.', [], 'Modules.Facetedsearch.Admin'), 'data' => $data['is_indexable']]);
    }
}